FROM martinussuherman/alpine-code-server:3.12.0-alpine3.13-amd64

RUN \
   apk --no-cache --update add \
   php7 \
   php7-bcmath \
   php7-ctype \
   php7-fileinfo \
   php7-json \
   php7-mbstring \
   php7-openssl \
   php7-pdo \
   php7-tokenizer \
   php7-xml
